### ISSUE TITLE
Log error with MarkdownHelper on queue/run

### ISSUE THREAD

**Issue by marc-farre** [StevenJoynt/HumHub-RSS-Reader#20]
Log:
```
Could not execute queued job! Message: DOMDocument::loadHTML(): Empty string supplied as input Trace:#0 [internal function]: yii\base\ErrorHandler->handleError()
#1 /app/data/modules/rss/components/MarkdownHelper.php(43): DOMDocument->loadHTML()
#2 /app/data/modules/rss/jobs/GetFeedUpdates.php(180): sij\humhub\modules\rss\components\MarkdownHelper::translateHTML()
#3 /app/data/modules/rss/jobs/GetFeedUpdates.php(280): sij\humhub\modules\rss\jobs\GetFeedUpdates->parseNewsItem()
#4 [internal function]: sij\humhub\modules\rss\jobs\GetFeedUpdates->parseNewsChannel()
#5 /app/data/modules/rss/components/RssElement.php(54): call_user_func()
#6 /app/data/modules/rss/jobs/GetFeedUpdates.php(326): sij\humhub\modules\rss\components\RssElement->each()
#7 /app/data/modules/rss/jobs/GetFeedUpdates.php(408): sij\humhub\modules\rss\jobs\GetFeedUpdates->parseNewsFeed()
#8 /app/data/modules/rss/jobs/GetFeedUpdates.php(449): sij\humhub\modules\rss\jobs\GetFeedUpdates->downloadNewsFeed()
#9 /app/code/protected/humhub/modules/queue/ActiveJob.php(33): sij\humhub\modules\rss\jobs\GetFeedUpdates->run()
#10 /app/code/protected/vendor/yiisoft/yii2-queue/src/Queue.php(246): humhub\modules\queue\ActiveJob->execute()
#11 /app/code/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage()
#12 /app/code/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(83): yii\queue\cli\Queue->handleMessage()
#13 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}()
#14 /app/code/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func()
#15 /app/code/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(93): yii\queue\cli\Queue->runWorker()
#16 /app/code/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Command.php(56): yii\queue\db\Queue->run()
#17 [internal function]: yii\queue\db\Command->actionRun()
#18 /app/code/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#19 /app/code/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#20 /app/code/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction()
#21 /app/code/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction()
#22 /app/code/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction()
#23 /app/code/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction()
#24 /app/code/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest()
#25 /app/code/protected/yii(29): yii\base\Application->run()
#26 {main}
```

Maybe just at the beginning of [the `translateHTML` method](https://github.com/StevenJoynt/HumHub-RSS-Reader/blob/7cab7ad46b26108e59f798cbdd50e750ba30aa93/components/MarkdownHelper.php#L39) we should add:
```
        if (!$html) {
            return '';
        }
```

**Comment by StevenJoynt** [comment]
Trace shows
#2 /app/data/modules/rss/jobs/GetFeedUpdates.php(180): sij\humhub\modules\rss\components\MarkdownHelper::translateHTML()

There isn't a call to translateHTML on line 180 of GetFeedUpdates in my version - it's later on at line 198. Has some code been deleted by accident?

Simply returning an empty string will stop the exception happening, but it looks like something has gone wrong earlier - the feed should have some contents or it's not a feed! It's probably right that an exception is being thrown in this case.

Is this a feed that has worked ok in the past? Can you access the feed using a different reader app or browser to see what should be displayed?

**Comment by marc-farre** [comment]
Thanks.
I'm sorry, but I don't have enough time to investigate and it's not installed on a Humhub that I manage.
The line number was different because it was the version 1.0.0.
I updated the module version to 1.0.2 and now I have this error:

```
[](https://hub.transition-space.org/admin/logging#)Could not execute queued job! Message: DOMDocument::loadHTML(): Empty string supplied as input Trace:#0 [internal function]: yii\base\ErrorHandler->handleError()
#1 /app/data/modules/rss/components/MarkdownHelper.php(43): DOMDocument->loadHTML()
#2 /app/data/modules/rss/jobs/GetFeedUpdates.php(198): sij\humhub\modules\rss\components\MarkdownHelper::translateHTML()
#3 /app/data/modules/rss/jobs/GetFeedUpdates.php(301): sij\humhub\modules\rss\jobs\GetFeedUpdates->parseNewsItem()
#4 [internal function]: sij\humhub\modules\rss\jobs\GetFeedUpdates->parseNewsChannel()
#5 /app/data/modules/rss/components/RssElement.php(54): call_user_func()
#6 /app/data/modules/rss/jobs/GetFeedUpdates.php(347): sij\humhub\modules\rss\components\RssElement->each()
#7 /app/data/modules/rss/jobs/GetFeedUpdates.php(429): sij\humhub\modules\rss\jobs\GetFeedUpdates->parseNewsFeed()
#8 /app/data/modules/rss/jobs/GetFeedUpdates.php(475): sij\humhub\modules\rss\jobs\GetFeedUpdates->downloadNewsFeed()
#9 /app/code/protected/humhub/modules/queue/ActiveJob.php(33): sij\humhub\modules\rss\jobs\GetFeedUpdates->run()
#10 /app/code/protected/vendor/yiisoft/yii2-queue/src/Queue.php(246): humhub\modules\queue\ActiveJob->execute()
#11 /app/code/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage()
#12 /app/code/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(83): yii\queue\cli\Queue->handleMessage()
#13 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}()
#14 /app/code/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func()
#15 /app/code/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(93): yii\queue\cli\Queue->runWorker()
#16 /app/code/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Command.php(56): yii\queue\db\Queue->run()
#17 [internal function]: yii\queue\db\Command->actionRun()
#18 /app/code/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#19 /app/code/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#20 /app/code/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction()
#21 /app/code/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction()
#22 /app/code/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction()
#23 /app/code/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction()
#24 /app/code/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest()
#25 /app/code/protected/yii(29): yii\base\Application->run()
#26 {main}
```

**Comment by StevenJoynt** [comment]
Could you tell me the URL of the RSS feed, so I can investigate the problem?

**Comment by marc-farre** [comment]
https://transitionnetwork.org/feed/

![image](https://user-images.githubusercontent.com/23310825/163670661-f7aa9d49-3b5b-491a-be8e-14234a1ab7e7.png)

Thanks.

**Comment by ArchBlood** [comment]
@funkycram I'll look at it later tonight if that's okay with @StevenJoynt

**Comment by ArchBlood** [comment]
@funkycram could you have your client try the following and see if it works?

[MarkdownHelper.zip](https://github.com/StevenJoynt/HumHub-RSS-Reader/files/9274305/MarkdownHelper.zip)

**Comment by marc-farre** [comment]
Thanks @ArchBlood .
This file seems to have confusions between static and non static variables.
E.g. the variable `public static $logFileHandle` is called by `private static function log($text)` with `$this->logFileHandle`.
It should be `static::$logFileHandle`

**Comment by marc-farre** [comment]
Thanks @ArchBlood .
This file seems to have confusions between static and non static variables.
E.g. the variable `public static $logFileHandle` is called by `private static function log($text)` with `$this->logFileHandle`.
It should be `static::$logFileHandle`

**Comment by ArchBlood** [comment]
> Thanks @ArchBlood .
> This file seems to have confusions between static and non static variables.
> E.g. the variable `public static $logFileHandle` is called by `private static function log($text)` with `$this->logFileHandle`.
> It should be `static::$logFileHandle`

Yes, originally I was going to use `static::logFileHandle` using `$` shouldn't make much of a difference should it? Overall I believe that the file itself could be retouched and refactored better. :thinking:

**Comment by ArchBlood** [comment]
So in turn the following should be displayed, once jobs run I see no errors actively;

```php
    private static function log($text) {
        if (static::logFileHandle) {
            fwrite(static::logFileHandle, $text);
        }
    }
```
I would also like to note that the other way didn't show any types of errors either, but only tested with PHP 8.0.x, further test on other versions would be recommended as well.

**Comment by marc-farre** [comment]
Then, what is the difference with your new `MarkdownHelper` class that could solve the bug?
See diff merge here: https://www.diffchecker.com/Y4URXxmJ

Thanks.

**Comment by ArchBlood** [comment]
> Then, what is the difference with your new `MarkdownHelper` class that could solve the bug?
> See diff merge here: https://www.diffchecker.com/Y4URXxmJ
> 
> Thanks.

`$this->` calls the public function, whether it's static or not, within the class, that's about it.

**Comment by ArchBlood** [comment]
Here's another example;

```php
<?php

class greeting
{
  public static function welcome()
 {
    echo "Hello World!";
  }

  public function __construct()
 {
    self::welcome();
  }
}

new greeting();
?>
```
You'll always get the response `Hello World!` this way, the same can be said for variable functions when using `$this->` in place of using the standard `self::` or `static::`.

**Comment by marc-farre** [comment]
OK, thanks, but I cannot see the difference with your new MarkdownHelper class that could solve this bug.
However, I tried your code, but now there are no error, with both codes (original and yours), so I cannot tell if it solves the bug.
Anyway, thanks for the code!
