### ISSUE TITLE
Error after activating module in space and clicking on configure

### ISSUE THREAD

**Issue by manuel-sauer** [StevenJoynt/HumHub-RSS-Reader#23]
Hi,
I love this humhub module!
However, after activating the module as an admin and activating it in a space, I clicked on configure, and an error came up saying:

"Oooops... It looks like you may have taken the wrong turn.
An internal server error occurred."

Maybe this error in logging can help you:

yii\base\UnknownMethodException: Calling unknown method: humhub\modules\space\models\Space::getSetting() in /homepages/12/d855780101/htdocs/hub/protected/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /homepages/12/d855780101/htdocs/hub/protected/modules/RSS/controllers/RssController.php(23): yii\base\Component->__call('getSetting', Array)
#1 [internal function]: sij\humhub\modules\rss\controllers\RssController->actionConfig()
#2 /homepages/12/d855780101/htdocs/hub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /homepages/12/d855780101/htdocs/hub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#4 /homepages/12/d855780101/htdocs/hub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('config', Array)
#5 /homepages/12/d855780101/htdocs/hub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('rss/rss/config', Array)
#6 /homepages/12/d855780101/htdocs/hub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(humhub\components\Request))
#7 /homepages/12/d855780101/htdocs/hub/index.php(26): yii\base\Application->run()
#8 {main}

I'm not quite sure if my HumHub version is the problem. I'm using HumHumb v1.13.1
Thanks a lot.

**Comment by ArchBlood** [comment]
The issue is `getSetting()` function is being called by `$container` for `Space::class` which doesn't exist, should be using `getSettings()`

https://github.com/humhub/humhub/blob/v1.14.0/protected/humhub/modules/space/models/Space.php#L654

Will also probably have issue with `setSetting()` because there's also no function for this either.
